version: '3'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apiserver
    restart: always
    ports:
      - 28800:8080
    volumes:
      - ./.env:/data/www/app/.env
      - ./static:/data/www/app/static:rw
    environment:
      - "REDIS_HOST=redis-server"
      - "MONGO_HOST=mongo-server"
      - "MYSQL_HOST=mysql-server"
      - "NATS_HOST=nats-server"
      - "DB_HOST=mongo-server:27017"
      - "DB_DRIVER=mongodb"
      - "NATS_URL=nats-server:4222"

    depends_on:
      - redis
      - mongodb
      - mysql
      - nats
    networks:
      - backend
      - forntend

  redis:
    hostname: redis-server
    image: redis:6.0.6-alpine
    container_name: redisserver
    restart: always
    ports:
      - 26379:6379
    networks:
      - backend
      - forntend

  mongodb:
    hostname: mongo-server
    image: mongo:4.2-bionic
    container_name: mongodbserver
    restart: always
    volumes:
      - ./data/mongodb/db:/data
    ports:
      - 37017:27017
    networks:
      - backend
      - forntend

  mysql:
    hostname: mysql-server
    image: mariadb:10.5.5-focal
    container_name: mysqlserver
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MY_ROOT_PASSWORD}
    volumes:
      - ./data/mysql/db:/var/lib/mysql
    ports:
      - 13306:3306
    networks:
      - backend

  nats:
    hostname: nats-server
    image: nats:2.1.7-alpine3.11
    container_name: natsserver
    restart: always
    ports:
      - 18442:4222
      - 18222:8222
    networks:
      - backend
      - forntend

networks:
  backend:
    driver: bridge
  forntend:
    driver: bridge