version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apiserver
    restart: always
    ports:
      - 28800:8080
    volumes:
      - ./.env:/data/www/app/.env
      - ./static:/data/www/app/static:rw
    depends_on:
      - redis
      - mongodb
      - mysql
      - nats

  redis:
    image: redis:6.0.6-alpine
    container_name: redisserver
    restart: always
    ports:
      - 26379:6379

  mongodb:
    image: mongo:4.2-bionic
    container_name: mongodbserver
    restart: always
    volumes:
      - ./data/mongodb/db:/data
    ports:
      - 37017:27017

  mysql:
    image: mariadb:10.5.5-focal
    container_name: mysqlserver
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MY_ROOT_PASSWORD}
    volumes:
      - ./data/mysql/db:/var/lib/mysql
    ports:
      - 13306:3306

  nats:
    image: nats:2.1.7-alpine3.11
    container_name: natsserver
    restart: always
    ports:
      - 18442:4222
      - 18222:8222
