version: '3'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: travel-server
    image: weblinuxgame/travel-app:${IMG_VERSION:-v3.44}
    restart: always
    env_file:
      - ./data/.docker-pro.env
    volumes:
      - ./data/conf:/data/www/app/conf
      - ./data/envs/.pro.env:/data/www/app/.env
      - ./data/view:/data/www/app/view:rw
      - ./static:/data/www/app/static:rw
      #- /etc/localtime:/etc/localtime:ro
    ports:
      - "18000:8080"
    networks:
      - travel
    depends_on:
      - redis
      - mongodb
      #- mysql
      #- nats
      #- 159

  redis:
    hostname: redis-traval
    image: redis:6.0.6-alpine
    restart: always
    ports:
      - "26379:6379"
    volumes:
      - ./data/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis/run:/var/run:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      - "TZ=Asia/Shanghai"
    networks:
      - travel
    entrypoint: [ "redis-server","/usr/local/etc/redis/redis.conf" ]

  mongodb:
    hostname: mongo-travel
    image: mongo:3.6.0
    restart: always
    privileged: true
    environment:
      TZ: Asia/Shanghai
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT:-mongodb}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-mongodb}
      MONGO_INITDB_ROOT_DATABASE: ${MONGO_ROOT_DB:-mongodb}
      APP_DB_NAME: travel
      APP_DB_USER: travel
      APP_DB_PASSWORD: travel
      APP_DB_RESTORE: false
    volumes:
      - ./data/mongodb/log:/var/log/mongodb:rw
      - ./data/mongodb/init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      #- ./data/mongodb/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh:ro
      #- ./data/mongodb/travel:/data/init:rw
    ports:
      - "37017:27017"
    networks:
      - travel

networks:
  travel:
    external: true