version: '3'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api-server
    image: weblinuxgame/travel-app:v3.15
    container_name: apiserver
    restart: always
    env_file:
      - ./data/.docker-pro.env
    volumes:
      - ./data/conf:/data/www/app/conf
      - ./data/envs/.pro.env:/data/www/app/.env
      - ./data/view:/data/www/app/view:rw
      - ./static:/data/www/app/static:rw
    ports:
      - 18000:8080
    networks:
      - travel
    depends_on:
      - redis
      - mongodb
      - mysql
      - nats

  redis:
    hostname: redis-server
    image: redis:6.0.6-alpine
    container_name: redisserver
    restart: always
    ports:
      - 26379:6379
    volumes:
      - ./data/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis/run:/var/run:rw
    networks:
      - travel
    entrypoint: ["redis-server","/usr/local/etc/redis/redis.conf"]

  mongodb:
    hostname: mongo-server
    image: mongo:4.2-bionic
    container_name: mongodbserver
    restart: always
    volumes:
      - ./data/mongodb:/data:rw
      - ./data/mongodb/config/mongodb.conf:/etc/mongod.conf.orig
    ports:
      - 37017:27017
    networks:
      - travel

  mysql:
    hostname: mysql-server
    image: mariadb:10.5.5-focal
    container_name: mysqlserver
    restart: always
    env_file:
      - ./data/.env
    volumes:
      - ./data/mysql/db:/var/lib/mysql
    ports:
      - 13306:3306
    networks:
      - travel

  nats:
    hostname: nats-server
    image: nats:2.1.7-alpine3.11
    container_name: natsserver
    restart: always
    ports:
      - 24442:4222
      - 28222:8222
      - 26222:6222
    networks:
      - travel

networks:
  travel:
    external: true